os: linux
dist: xenial # Use Ubuntu 16.04 as our Travis CI environment
language: python # Python is the programming language, of course
python: "2.7" # Use Python 2 since we write in it due to Wallaby using it
env: LEGOBOT_CODE="$TRAVIS_BUILD_DIR/Legobot Code" ROOMBA_CODE="$TRAVIS_BUILD_DIR/Roomba Code"

before_install:
  # Create directories if not present
  - mkdir -p "$LEGOBOT_CODE" "ROOMBA_CODE"

install:
  # Install required dependencies
  - pip install --upgrade pylint # Use pip to install Pylint

script:
  # Lint the Python files
  - pylint -j 4 -d missing-docstring,unused-wildcard-import,wildcard-import,unused-import,redefined-builtin "$LEGOBOT_CODE"/*.py "$ROOMBA_CODE"/*.py

notifications:
  slack: $SLACK_TOKEN
